blank_issues_enabled: false
contact_links:
  - name: 阅读BetterNCM/README.md
    url: https://github.com/Entity-122425111303/UnblockCloudMusic/blob/c35d976ca2ea3cfb3d38d668d65c4755ecfbb588/README.md
    about: Please read README.md first.
  - name: 阅读node.js/README.md
    url: https://github.com/Entity-122425111303/UnblockCloudMusic/blob/2e6dc3d3b488ea6776e0e44b89c313eab7de7ad6/README.md
    about: Please read README.md first.